
import { Animal, AnimalCategory, LogType, SystemPreferences, LocalBackupConfig } from './types';

export const DEFAULT_SYSTEM_PREFERENCES: any = {
  unit_system: 'Metric',
  temp_unit: 'C',
  dashboard_density: 'Standard',
  brand_colour: '#10b981',
  session_timeout_minutes: 5,
  auto_purge_days: 365
};

export const DEFAULT_LOCAL_BACKUP_CONFIG: any = {
  enabled: true,
  frequency: 'daily',
  retention_count: 7
};

export const SYSTEM_ANIMAL_ID = '00000000-0000-0000-0000-000000000000';

export const DEFAULT_FOOD_OPTIONS = {
  [AnimalCategory.OWLS]: ['Day Old Chick', 'Mouse', 'Rat', 'Quail', 'Rabbit'],
  [AnimalCategory.RAPTORS]: ['Day Old Chick', 'Mouse', 'Rat', 'Quail', 'Rabbit', 'Beef'],
  [AnimalCategory.MAMMALS]: ['Fruit Mix', 'Vegetables', 'Insects', 'Meat', 'Pellets', 'Egg'],
  [AnimalCategory.EXOTICS]: ['Mouse (Pinky)', 'Mouse (Fuzzie)', 'Rat', 'Insects', 'Salad'],
};

export const DEFAULT_FEED_METHODS = {
  [AnimalCategory.OWLS]: ['Hand', 'Tongs', 'Bowl', 'Scatter', 'Training', 'Plate'],
  [AnimalCategory.RAPTORS]: ['Hand', 'Tongs', 'Tethered', 'Plate'],
  [AnimalCategory.MAMMALS]: ['Bowl', 'Scatter', 'Hand', 'Hidden', 'Puzzle'],
  [AnimalCategory.EXOTICS]: ['Tongs', 'Bowl', 'Drop Feed'],
};

export const DEFAULT_EVENT_TYPES = [
    'Educational Talk',
    'Flying Display',
    'Experience Day',
    'Training Demo',
    'Off-Site Event',
    'School Visit',
    'Photography Session'
];

export const DEFAULT_ENRICHMENT_TYPES = [
    'Food - Scatter',
    'Food - Puzzle Feeder',
    'Food - Hidden',
    'Sensory - Scent',
    'Sensory - Sound',
    'Physical - Climbing',
    'Physical - Digging',
    'Physical - New Item',
    'Cognitive - Training',
    'Social - Group Interaction'
];

export const MOCK_ANIMALS: any[] = [
  {
    id: '1',
    name: 'Ghost',
    species: 'Barn Owl',
    latin_name: 'Tyto alba',
    category: AnimalCategory.OWLS,
    dob: new Date('2018-05-12'),
    location: 'Aviary 1',
    description: 'A gentle male Barn Owl used frequently for school visits.',
    special_requirements: 'Needs quiet environment during molt.',
    image_url: 'https://picsum.photos/seed/ghost/400/400',
    summer_weight_g: 310,
    winter_weight_g: 340,
    flying_weight_g: 320,
    ring_number: 'BTO-12345',
    weight_unit: 'g',
    is_dob_unknown: false,
    sex: 'Male',
    acquisition_date: new Date('2018-05-12'),
    origin: 'Unknown',
    is_venomous: false,
    hazard_rating: 'None',
    red_list_status: 'LC',
    archived: false,
    is_quarantine: false,
    display_order: 1,
    is_group_animal: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 'system',
    last_modified_by: 'system',
    logs: [],
    documents: []
  },
  {
    id: '2',
    name: 'Zeus',
    species: 'Golden Eagle',
    latin_name: 'Aquila chrysaetos',
    category: AnimalCategory.RAPTORS,
    dob: new Date('2015-03-20'),
    location: 'Main Weathering',
    description: 'Large male Golden Eagle. Very dominant.',
    special_requirements: 'Double tethering required.',
    image_url: 'https://picsum.photos/seed/zeus/400/400',
    summer_weight_g: 3800,
    winter_weight_g: 4200,
    flying_weight_g: 3950,
    ring_number: 'GE-9988',
    weight_unit: 'g',
    is_dob_unknown: false,
    sex: 'Male',
    acquisition_date: new Date('2015-03-20'),
    origin: 'Unknown',
    is_venomous: false,
    hazard_rating: 'None',
    red_list_status: 'LC',
    archived: false,
    is_quarantine: false,
    display_order: 2,
    is_group_animal: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 'system',
    last_modified_by: 'system',
    logs: [],
    documents: []
  },
  {
    id: '3',
    name: 'Timon',
    species: 'Meerkat',
    latin_name: 'Suricata suricatta',
    category: AnimalCategory.MAMMALS,
    dob: new Date('2019-01-10'),
    location: 'Mammal Enclosure B',
    description: 'Alpha male of the mob.',
    special_requirements: 'Heat lamp check daily.',
    image_url: 'https://picsum.photos/seed/timon/400/400',
    summer_weight_g: 720,
    winter_weight_g: 750,
    flying_weight_g: 0,
    weight_unit: 'g',
    is_dob_unknown: false,
    sex: 'Male',
    acquisition_date: new Date('2019-01-10'),
    origin: 'Unknown',
    is_venomous: false,
    hazard_rating: 'None',
    red_list_status: 'LC',
    archived: false,
    is_quarantine: false,
    display_order: 3,
    is_group_animal: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 'system',
    last_modified_by: 'system',
    logs: [],
    documents: []
  },
  {
    id: '4',
    name: 'Slinky',
    species: 'Corn Snake',
    latin_name: 'Pantherophis guttatus',
    category: AnimalCategory.EXOTICS,
    dob: new Date('2020-07-22'),
    location: 'Reptile Room',
    description: 'Orange albino corn snake.',
    special_requirements: 'Feed separately from tank.',
    image_url: 'https://picsum.photos/seed/slinky/400/400',
    summer_weight_g: 450,
    winter_weight_g: 450,
    flying_weight_g: 0,
    target_day_temp_c: 28,
    target_night_temp_c: 22,
    weight_unit: 'g',
    is_dob_unknown: false,
    sex: 'Unknown',
    acquisition_date: new Date('2020-07-22'),
    origin: 'Unknown',
    is_venomous: false,
    hazard_rating: 'None',
    red_list_status: 'LC',
    archived: false,
    is_quarantine: false,
    display_order: 4,
    is_group_animal: false,
    created_at: new Date(),
    updated_at: new Date(),
    created_by: 'system',
    last_modified_by: 'system',
    logs: [],
    documents: []
  }
];
